# Generated by Django 4.0.4 on 2022-05-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtaChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ata_digit', models.CharField(max_length=10)),
                ('ata_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note_for_examiner', models.CharField(max_length=50)),
                ('ata_chapters', models.ManyToManyField(to='mcq_gen.atachapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='mcq_gen.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('level', models.IntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('checked', models.BooleanField(default=False)),
                ('book_page', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('check_date', models.DateField(blank=True, null=True)),
                ('change_date', models.DateField(blank=True, null=True)),
                ('ref_to_old_id', models.IntegerField(default=0)),
                ('ref_to_new_id', models.IntegerField(default=0)),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('disable_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('ata_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mcq_gen.atachapter')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='mcq_gen.course')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_number', models.IntegerField()),
                ('level', models.IntegerField()),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='mcq_gen.atachapter')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='mcq_gen.training')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='mcq_gen.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='mcq_gen.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('test_field', models.IntegerField(default=None)),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mcq_gen.exam')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mcq_gen.question')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mcq_gen.student')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='mcq_gen.training'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='mcq_gen.question'),
        ),
        migrations.AddField(
            model_name='course',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='mcq_gen.training'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default=False, max_length=400)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mcq_gen.question')),
            ],
        ),
    ]
