# Generated by Django 4.0.4 on 2022-04-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtaChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ata_digit', models.CharField(max_length=10)),
                ('ata_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_reexam', models.BooleanField(default=False)),
                ('note_for_examiner', models.CharField(max_length=50)),
                ('ata_chapters', models.ManyToManyField(to='mcq_gen.atachapters')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='mcq_gen.course')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='mcq_gen.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('checked', models.BooleanField(default=False)),
                ('book_page', models.CharField(max_length=20)),
                ('issue_date', models.DateField(null=True)),
                ('check_date', models.DateField(null=True)),
                ('change_date', models.DateField(null=True)),
                ('ref_to_old_id', models.IntegerField(default=0)),
                ('ref_to_new_id', models.IntegerField(default=0)),
                ('issued_by', models.CharField(max_length=30, null=True)),
                ('checked_by', models.CharField(max_length=30, null=True)),
                ('changed_by', models.CharField(max_length=30, null=True)),
                ('disable_reason', models.CharField(max_length=200, null=True)),
                ('ata_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mcq_gen.atachapters')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='mcq_gen.training')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='mcq_gen.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_exam', to='mcq_gen.question')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='mcq_gen.training'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mcq_gen.question')),
            ],
        ),
    ]
