# Generated by Django 4.0.4 on 2022-04-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_gen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtaChapters',
            new_name='AtaChapter',
        ),
    ]
