# Generated by Django 4.0.4 on 2022-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
