# Generated by Django 4.0.4 on 2022-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atachapter',
            name='ata_description',
            field=models.CharField(max_length=300),
        ),
    ]
