# Generated by Django 4.0.4 on 2022-04-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_gen', '0002_rename_atachapters_atachapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='changed_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='checked_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='disable_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='issued_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
