# Generated by Django 4.0.4 on 2022-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_gen', '0002_alter_question_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsequence',
            name='sequence_number',
            field=models.IntegerField(verbose_name='Seq. number'),
        ),
    ]
