# Generated by Django 4.0.4 on 2022-04-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_gen', '0003_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='book_page',
            field=models.CharField(max_length=100),
        ),
    ]
