# Generated by Django 4.0.4 on 2022-04-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_gen', '0003_alter_question_change_date_alter_question_changed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_number', models.IntegerField()),
                ('level', models.IntegerField()),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='mcq_gen.atachapter')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='mcq_gen.training')),
            ],
        ),
    ]
