# Generated by Django 4.0.4 on 2022-04-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_gen', '0004_remove_question_level_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
