# Generated by Django 4.0.4 on 2022-04-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_gen', '0004_alter_question_book_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='changed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='checked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='issued_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
