# Generated by Django 4.0.4 on 2022-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_gen', '0008_alter_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('exam', models.ManyToManyField(to='mcq_gen.exam')),
                ('question', models.ManyToManyField(to='mcq_gen.question')),
            ],
        ),
    ]
